spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pulda?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: local
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server.port: 8088
